# Generated by Django 5.0.2 on 2024-02-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_title', models.CharField(max_length=100)),
                ('issue_description', models.TextField()),
                ('os', models.CharField(choices=[('windows', 'Windows'), ('mac', 'Mac'), ('linux', 'Linux'), ('other', 'Other')], max_length=20)),
                ('browser', models.CharField(max_length=20)),
                ('assigned_to', models.CharField(max_length=20)),
                ('priority', models.CharField(max_length=20)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='main')),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
